/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/art.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0}>
        <group position={[-272.4, 32.64, -327.76]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['norway_02_-_Default_0'].geometry} material={materials['Material.002']} position={[286.73, -313.88, 0]} scale={[1, 1, 1.54]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/art.glb')
