/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/boat.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.99}>
        <group position={[0, 2.38, 1.7]} rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]} />
        </group>
        <mesh geometry={nodes.Victorian_Row_Boat_Boat_Glossy_0.geometry} material={materials.Boat_Glossy} />
        <mesh geometry={nodes.Victorian_Row_Boat_Boat_Metal_0.geometry} material={materials.Boat_Metal} />
        <mesh geometry={nodes.Victorian_Row_Boat_Boat_Tex_0.geometry} material={materials.Boat_Tex} />
        <mesh geometry={nodes.Victorian_Row_Boat_Brillo_0.geometry} material={materials.Brillo} />
      </group>
    </group>
  )
}

useGLTF.preload('/boat.glb')
