/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/cloud1.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Icosphere006.geometry} material={nodes.Icosphere006.material} position={[-3.32, 3.3, -2.15]} rotation={[-3.14, 1.02, 0]} scale={0.2} />
      <mesh geometry={nodes.Icosphere009.geometry} material={nodes.Icosphere009.material} position={[-3.91, 2.7, -0.71]} rotation={[0, 1.02, 0]} scale={0.2} />
    </group>
  )
}

useGLTF.preload('/cloud1.glb')
