/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/cloudClose.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Icosphere003.geometry} material={nodes.Icosphere003.material} position={[-3.05, 5.29, -0.34]} rotation={[0, -1.03, Math.PI]} scale={0.2} />
      <mesh geometry={nodes.Icosphere004.geometry} material={nodes.Icosphere004.material} position={[-1.77, 3.12, -3.67]} rotation={[0, 1.02, 0]} scale={0.2} />
      <mesh geometry={nodes.Icosphere005.geometry} material={nodes.Icosphere005.material} position={[-0.29, 4.54, -2.3]} rotation={[-Math.PI, 1.02, 0]} scale={0.2} />
      <mesh geometry={nodes.Icosphere006.geometry} material={nodes.Icosphere006.material} position={[-3.32, 3.3, -2.15]} rotation={[-3.14, 1.02, 0]} scale={0.2} />
      <mesh geometry={nodes.Icosphere007.geometry} material={nodes.Icosphere007.material} position={[-1.99, 5.22, -1.29]} rotation={[-Math.PI, 1.39, 0]} scale={0.2} />
      <mesh geometry={nodes.Icosphere009.geometry} material={nodes.Icosphere009.material} position={[-3.91, 2.7, -0.71]} rotation={[0, 1.02, 0]} scale={0.2} />
    </group>
  )
}

useGLTF.preload('/cloudClose.glb')
