/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/sky.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['GeoSphere001_10_-_Default_0'].geometry} material={materials['10_-_Default']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/sky.glb')
